#docker-composeのバージョン
version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/myproject
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379
  db:
    image: postgres
    ports:
      - '54333:5432' # 54333に指定している理由は、dbクライアントから接続するときにlocalとコンフリクトしないため。参照：https://www.youtube.com/watch?v=BHniRaZ0_JE
    volumes:
      - postgresql-data:/var/lib/postgresql/data:delegated
    # passwordを設定しないと接続できない。参照： https://qiita.com/at-946/items/2fb75cec5355fad4050d
    environment:
      # - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'" # A server is already running.と怒られる問題の解決：https://qiita.com/paranishian/items/862ce4de104992df48e1
    tty: true
    stdin_open: true
    depends_on:
      - db # DB側のコンテナが出来上がってからwebを実行する
      - chrome
    ports:
      - "3000:3000" # ホストからゲストへポートフォワード
      # Ports required for debugging. RubyMineのデバッグ用。参考：https://www.youtube.com/watch?v=BHniRaZ0_JE
      - "1234:1234"
      - "26166:26168"
    volumes:
      - .:/myproject:delegated # ソースコード変更したらDocker側も即反映されるようにする。また:cachedをつけることで読込を早くする。
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
volumes:
  postgresql-data:
    driver: local