:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 7

:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
  - [ often, 7 ]
  - [ default, 5 ]
  - [ seldom, 3 ]
  - [ mailers, 9 ]
  #追加した/ https://programing-school.work/rubyrails-redis-sidekiq-deliver_later-queue/
  #以下、deliver_laterでメールが送信できなかった問題を解決しようとした結果。
  # http://totutotu.hatenablog.com/entry/2015/09/02/ActionMailer%E3%81%AE%E9%9D%9E%E5%90%8C%E6%9C%9F%E5%87%A6%E7%90%86%E3%82%92%E3%82%92ActiveJob%2BSidekiq%E3%81%A7
  #:daemon: true
  # bundle exec sidekiq -C config/sidekiq.yml